@echo off

REM ---- Options ----
set CMAKE_GENERATOR_VS=vs
set CMAKE_GENERATOR_NINJA=ninja

set VCPKG_BINARY_CACHING_TYPE_NONE=none
set VCPKG_BINARY_CACHING_TYPE_NUGET_READ=nuget_read
set VCPKG_BINARY_CACHING_TYPE_NUGET_READ_WRITE=nuget_readwrite
set VCPKG_BINARY_CACHING_TYPE_DEFAULT=

REM ---- Local values: update path when running locally ----
set "CI_CD_BUILDTOOLS_ROOT=d:\nuget"
set "NUGET_EXE=D:\Software\nuget\5.5\bin\nuget.exe"
set VCPKG_BINARY_CACHING=%VCPKG_BINARY_CACHING_TYPE_NONE%
set CMAKE_GENERATOR=%CMAKE_GENERATOR_NINJA%
set VCPKG_BINARY_CACHING_TYPE=%VCPKG_BINARY_CACHING_TYPE_DEFAULT%
set "DOTNET_ROOT=%CI_CD_BUILDTOOLS_ROOT%/%DOTNET_SDK_PACKAGE%.%DOTNET_SDK_VERSION%"

